import { useEffect } from 'react';
import { ThemeProvider } from '@material-ui/core/styles'
import { CssBaseline } from '@material-ui/core'
import PropTypes from 'prop-types'
import Head from 'next/head'
import theme from '../../styles/theme'
import '../../styles/globals.css'

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);
  
  return <>
    <Head>
      <title>APIED LTD</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ThemeProvider theme={theme}>
      {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
      <CssBaseline />
      <Component {...pageProps} />
  </ThemeProvider>
  </>
  
}

MyApp.propTypes = {
  Component: PropTypes.Component,
  pageProps: PropTypes.any
}

export default MyApp
