/* eslint-disable no-undef */
/* eslint-disable react/forbid-prop-types */
import React, { useEffect } from 'react';
import { ThemeProvider } from '@material-ui/core/styles'
import { CssBaseline } from '@material-ui/core'
import PropTypes from 'prop-types'
import Head from 'next/head'
import {theme} from '../../styles/theme'
import '../../styles/globals.css'
import ContextProvider from '../context/Context'

function MyApp({ Component, pageProps }) {
  const Layout = Component.Layout ? Component.Layout : React.Fragment
  useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);
  
  return <ContextProvider>
    <ThemeProvider theme={theme}>
      <Layout>
        <Head>
          <title>APIED LTD</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
          <CssBaseline />
          <Component {...pageProps} />
      </Layout>
    </ThemeProvider>
  </ContextProvider>
  
}

MyApp.propTypes = {
  Component: PropTypes.func,
  pageProps: PropTypes.any
}

export default MyApp
