import { ThemeProvider } from '@material-ui/styles'
import Head from 'next/head'
import HomePage from '../common/components/home/Home'
import styles from '../../styles/Home.module.css'
import theme from '../../styles/theme'

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <title>APIED LTD</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomePage />
      </div>
    </ThemeProvider>
  )
}
