version: "3.8"
services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=wrace
      - POSTGRES_PASSWORD=wrace
      - POSTGRES_DB=wrace
      - NODE_ENV=development
    ports:
      - 5430:5432
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data

  app:
    build: ./app
    depends_on:
      - db
    environment: 
      # - PORT=$API_PORT
      # - PGHOST=db
      # - PGPORT=$DB_PORT
      # - PGUSER=$DB_USER
      # - PGPASSWORD=$DB_PASSWORD
      # - PGDATABASE=$DB_NAME
      - DB_PORT=5432
      - DB_USER=wrace
      - DB_PASSWORD=wrace
      - DB_NAME=wrace
      - DB_HOST=db
      - DB_HOST_TEST=wrace_test
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    command: sh -c "yarn dev"
    restart: on-failure

  # app:
  #   build: ./app
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./app:/app
  #     - /app/node_modules
  #     - /app/.next
  #   stdin_open: true
  #   command: yarn dev

  # test_api:
  #   build: ./api
  #   environment:
  #     - NODE_ENV=test
  #     - POSTGRES_DB=tts_test
  #   command: yarn test:coverage
