FROM node:15.14.0

WORKDIR /api
ENV PATH /node_modules/.bin:$PATH

ADD package*.json ./

RUN yarn
RUN yarn add sequelize-cli

ADD yarn.lock ./

ADD .sequelizerc ./

ADD .babelrc ./

ENV NODE_ENV=production
COPY . .

# CMD ["yarn", "start"]
